service: sample-lambda-layer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}

layers: '${file(src/serverless-resources/layers.yml)}'